version: '3'
services:
  app:
    container_name: node-api
    restart: always
    build: .
    ports:
      - '3000:3000'
    link:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    